"""add_intelligence_tables

Revision ID: 5c34068cd4e0
Revises: 20260611_0003
Create Date: 2026-06-24 10:32:32.486405
"""
from alembic import op
import sqlalchemy as sa


revision = '5c34068cd4e0'
down_revision = '20260611_0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_field_registry',
    sa.Column('field_key', sa.String(length=128), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_field_registry_field_key'), 'knowledge_field_registry', ['field_key'], unique=True)
    op.create_table('startup_intelligence_profiles',
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startup_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_intelligence_profiles_startup_id'), 'startup_intelligence_profiles', ['startup_id'], unique=True)
    op.create_table('startup_processing_status',
    sa.Column('startup_id', sa.Uuid(), nullable=False),
    sa.Column('pipeline_name', sa.String(length=128), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'WAITING_FOR_AI', 'WAITING_FOR_RETRY', 'COMPLETED', 'FAILED', 'CANCELLED', name='pipelinestatus', native_enum=False, length=32), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['startup_id'], ['startup_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_processing_status_startup_id'), 'startup_processing_status', ['startup_id'], unique=False)
    op.create_index(op.f('ix_startup_processing_status_status'), 'startup_processing_status', ['status'], unique=False)
    op.create_table('field_conflicts',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['knowledge_field_registry.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['startup_intelligence_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_conflicts_field_id'), 'field_conflicts', ['field_id'], unique=False)
    op.create_index(op.f('ix_field_conflicts_profile_id'), 'field_conflicts', ['profile_id'], unique=False)
    op.create_index(op.f('ix_field_conflicts_resolved'), 'field_conflicts', ['resolved'], unique=False)
    op.create_table('startup_claims',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('value_string', sa.String(length=1000), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence_reason', sa.Text(), nullable=True),
    sa.Column('merge_reason', sa.Text(), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['knowledge_field_registry.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_id'], ['startup_intelligence_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_claims_field_id'), 'startup_claims', ['field_id'], unique=False)
    op.create_index(op.f('ix_startup_claims_is_preferred'), 'startup_claims', ['is_preferred'], unique=False)
    op.create_index(op.f('ix_startup_claims_profile_id'), 'startup_claims', ['profile_id'], unique=False)
    op.create_table('startup_intelligence_profile_versions',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('profile_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['startup_intelligence_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_intelligence_profile_versions_profile_id'), 'startup_intelligence_profile_versions', ['profile_id'], unique=False)
    op.create_table('field_sources',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['startup_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_sources_claim_id'), 'field_sources', ['claim_id'], unique=False)
    op.create_index(op.f('ix_field_sources_document_id'), 'field_sources', ['document_id'], unique=False)
    op.create_table('field_versions',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('value_string', sa.String(length=1000), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['claim_id'], ['startup_claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_versions_claim_id'), 'field_versions', ['claim_id'], unique=False)
    op.create_table('startup_evidence',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('evidence_snippet', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['startup_claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_startup_evidence_claim_id'), 'startup_evidence', ['claim_id'], unique=False)
    op.create_index(op.f('ix_startup_evidence_source_document_id'), 'startup_evidence', ['source_document_id'], unique=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_startup_evidence_source_document_id'), table_name='startup_evidence')
    op.drop_index(op.f('ix_startup_evidence_claim_id'), table_name='startup_evidence')
    op.drop_table('startup_evidence')
    op.drop_index(op.f('ix_field_versions_claim_id'), table_name='field_versions')
    op.drop_table('field_versions')
    op.drop_index(op.f('ix_field_sources_document_id'), table_name='field_sources')
    op.drop_index(op.f('ix_field_sources_claim_id'), table_name='field_sources')
    op.drop_table('field_sources')
    op.drop_index(op.f('ix_startup_intelligence_profile_versions_profile_id'), table_name='startup_intelligence_profile_versions')
    op.drop_table('startup_intelligence_profile_versions')
    op.drop_index(op.f('ix_startup_claims_profile_id'), table_name='startup_claims')
    op.drop_index(op.f('ix_startup_claims_is_preferred'), table_name='startup_claims')
    op.drop_index(op.f('ix_startup_claims_field_id'), table_name='startup_claims')
    op.drop_table('startup_claims')
    op.drop_index(op.f('ix_field_conflicts_resolved'), table_name='field_conflicts')
    op.drop_index(op.f('ix_field_conflicts_profile_id'), table_name='field_conflicts')
    op.drop_index(op.f('ix_field_conflicts_field_id'), table_name='field_conflicts')
    op.drop_table('field_conflicts')
    op.drop_index(op.f('ix_startup_processing_status_status'), table_name='startup_processing_status')
    op.drop_index(op.f('ix_startup_processing_status_startup_id'), table_name='startup_processing_status')
    op.drop_table('startup_processing_status')
    op.drop_index(op.f('ix_startup_intelligence_profiles_startup_id'), table_name='startup_intelligence_profiles')
    op.drop_table('startup_intelligence_profiles')
    op.drop_index(op.f('ix_knowledge_field_registry_field_key'), table_name='knowledge_field_registry')
    op.drop_table('knowledge_field_registry')
    # ### end Alembic commands ###

