# Templates for generating different sections of the Due Diligence Report

EXECUTIVE_TEMPLATE = """
# Due Diligence Report: {startup_name}
**Report ID**: {report_id}
**Startup ID**: {startup_id} (Profile Version: {profile_version})
**Generated At**: {generated_at}
**Generated By**: {generated_by}
**Graph Hash**: {graph_hash}

## Executive Summary
{overview}

### Overall Readiness
*   **Overall Score**: {overall_score}/100
*   **Overall Confidence**: {overall_confidence:.2f}
*   **Evidence Coverage**: {evidence_coverage:.2%}

### Investment Recommendation
{investment_recommendation}

### Top Strengths
{strengths}

### Critical Weaknesses
{weaknesses}
"""

DOMAIN_SECTION_TEMPLATE = """
## {title} Assessment
{summary}

*   **Section Confidence**: {confidence:.2f}

### Key Observations
{observations}

### Supporting Evidence
{evidence}

### Key Strengths
{strengths}

### Key Weaknesses
{weaknesses}

### Recommendations
{recommendations}

### Open Questions
{open_questions}
"""

RISK_MATRIX_TEMPLATE = """
## Risk Matrix
The following matrix details risk categories identified by the expert agents:

| Category | Severity | Confidence | Primary Evidence | Mitigation / Recommendation |
| --- | --- | --- | --- | --- |
| **Technical** | {tech_severity} | {tech_confidence:.2f} | {tech_evidence} | {tech_reco} |
| **Execution** | {exec_severity} | {exec_confidence:.2f} | {exec_evidence} | {exec_reco} |
| **Market** | {mkt_severity} | {mkt_confidence:.2f} | {mkt_evidence} | {mkt_reco} |
| **Competition** | {comp_severity} | {comp_confidence:.2f} | {comp_evidence} | {comp_reco} |
| **Financial** | {fin_severity} | {fin_confidence:.2f} | {fin_evidence} | {fin_reco} |
| **Regulatory** | {reg_severity} | {reg_confidence:.2f} | {reg_evidence} | {reg_reco} |
| **IP** | {ip_severity} | {ip_confidence:.2f} | {ip_evidence} | {ip_reco} |
"""

INVESTMENT_SUMMARY_TEMPLATE = """
## Investment Summary
*   **Investment Readiness**: {investment_readiness}
*   **Grant Readiness**: {grant_readiness}
*   **VC Readiness**: {vc_readiness}
*   **Technology Readiness Level (TRL)**: {trl}
*   **Portfolio Rank**: {portfolio_rank}
*   **Final Recommendation**: {recommendation}
"""

APPENDIX_TEMPLATE = """
## Appendix: Traceability & Audit Trail
This appendix documents the integrity check hashes and full system provenance traces for compliance and reproducibility.

### Verification Metadata
*   **Graph Hash**: `{graph_hash}`
*   **Profile Version**: `{profile_version}`
*   **Generated By**: {generated_by}

### Traceability Mapping
{traceability_markdown}
"""
