from abc import ABC, abstractmethod
from typing import Any
from app.modules.reporting.report_models import Report


class ReportRenderer(ABC):
    """Abstract base class for report format renderers."""

    @abstractmethod
    def render(self, report: Report) -> Any:
        """Render the given report model into a specific target format."""
        pass


class MarkdownRenderer(ReportRenderer):
    """Compiles all sections of a Report into a single well-formatted Markdown document."""

    def render(self, report: Report) -> str:
        parts = [
            f"# Due Diligence Report: {report.startup_name}",
            f"**Report ID:** `{report.report_id}`",
            f"**Startup ID:** `{report.startup_id}`",
            f"**Generated At:** {report.generated_at}",
            f"**Generated By:** {report.generated_by}",
            f"**Version:** {report.report_version}",
            f"**Integrity Hash:** `{report.report_hash}`",
            "",
            report.executive_summary,
            "",
            report.founder_analysis,
            "",
            report.product_analysis,
            "",
            report.market_analysis,
            "",
            report.competition_analysis,
            "",
            report.financial_analysis,
            "",
            report.trl_analysis,
            "",
            report.ip_analysis,
            "",
            report.risk_analysis,
            "",
            report.committee_decision,
            "",
            report.investment_recommendation,
            "",
            report.portfolio_position,
            "",
            report.explainability_appendix,
            "",
            report.evidence_appendix
        ]
        return "\n\n".join(parts)


class HTMLRenderer(ReportRenderer):
    """Converts the Report into a modern, responsive HTML page layout."""

    def render(self, report: Report) -> str:
        # Create a clean Markdown compilation first
        md_content = MarkdownRenderer().render(report)
        
        # Simple markdown to HTML conversion lines
        html_lines = []
        in_list = False
        
        for line in md_content.splitlines():
            line = line.strip()
            if not line:
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append("<br/>")
                continue
                
            if line.startswith("# "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h1>{line[2:]}</h1>")
            elif line.startswith("## "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h2>{line[3:]}</h2>")
            elif line.startswith("### "):
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                html_lines.append(f"<h3>{line[4:]}</h3>")
            elif line.startswith("*   ") or line.startswith("* "):
                if not in_list:
                    html_lines.append("<ul>")
                    in_list = True
                content = line[4:] if line.startswith("*   ") else line[2:]
                html_lines.append(f"<li>{content}</li>")
            else:
                if in_list:
                    html_lines.append("</ul>")
                    in_list = False
                processed = line
                # bold replacement
                processed = processed.replace("**", "<strong>", 1).replace("**", "</strong>", 1)
                # inline code
                processed = processed.replace("`", "<code>", 1).replace("`", "</code>", 1)
                html_lines.append(f"<p>{processed}</p>")
                
        if in_list:
            html_lines.append("</ul>")
            
        html_body = "\n".join(html_lines)

        html_template = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Due Diligence Report - {report.startup_name}</title>
    <style>
        body {{
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            color: #333333;
            line-height: 1.6;
            max-width: 900px;
            margin: 40px auto;
            padding: 0 20px;
            background-color: #f8f9fa;
        }}
        .container {{
            background: #ffffff;
            padding: 40px;
            border-radius: 8px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        h1 {{
            color: #1a365d;
            border-bottom: 2px solid #2b6cb0;
            padding-bottom: 10px;
            margin-top: 40px;
        }}
        h2 {{
            color: #2c5282;
            margin-top: 30px;
            border-bottom: 1px solid #e2e8f0;
            padding-bottom: 8px;
        }}
        h3 {{
            color: #4a5568;
            margin-top: 20px;
        }}
        code {{
            background: #edf2f7;
            padding: 2px 6px;
            border-radius: 4px;
            font-family: SFMono-Regular, Consolas, "Liberation Mono", Menlo, Courier, monospace;
            font-size: 0.9em;
        }}
        li {{
            margin-bottom: 8px;
        }}
        strong {{
            color: #2d3748;
        }}
    </style>
</head>
<body>
    <div class="container">
        {html_body}
    </div>
</body>
</html>
"""
        return html_template


class JSONRenderer(ReportRenderer):
    """Serializes the Report model into a deterministic JSON format."""

    def render(self, report: Report) -> str:
        if hasattr(report, "model_dump_json"):
            return report.model_dump_json(indent=2)
        if hasattr(report, "json"):
            return report.json(indent=2)
        import json
        return json.dumps(report, default=str, indent=2)
