from typing import Any
from app.modules.reporting.report_models import DueDiligenceReport
from app.modules.reporting.report_renderer import MarkdownRenderer, HTMLRenderer, JSONRenderer


class ReportExporter:
    """Exports DueDiligenceReport and Report models to JSON, Markdown, HTML, PDF, and DOCX formats."""

    @staticmethod
    def export_to_json(report: Any, file_path: str) -> None:
        content = JSONRenderer().render(report)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    @staticmethod
    def export_to_markdown(report: Any, file_path: str) -> None:
        content = MarkdownRenderer().render(report)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    @staticmethod
    def export_to_html(report: Any, file_path: str) -> None:
        content = HTMLRenderer().render(report)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)

    @staticmethod
    def export_to_docx(report: Any, file_path: str) -> None:
        import docx
        doc = docx.Document()

        doc.add_heading(f"Due Diligence Report: {report.startup_name}", 0)
        doc.add_paragraph(f"Report ID: {report.report_id}")
        doc.add_paragraph(f"Startup ID: {report.startup_id}")
        doc.add_paragraph(f"Generated At: {report.generated_at}")
        doc.add_paragraph(f"Generated By: {report.generated_by}")
        doc.add_paragraph(f"Graph Hash: {getattr(report, 'graph_hash', 'N/A')}")

        doc.add_heading("Executive Summary", level=1)
        doc.add_paragraph(getattr(report, "executive_summary", ""))

        if isinstance(report, DueDiligenceReport):
            # Investment Summary
            doc.add_heading("Investment Summary", level=1)
            doc.add_paragraph(f"Investment Readiness: {report.investment_summary.investment_readiness}")
            doc.add_paragraph(f"Grant Readiness: {report.investment_summary.grant_readiness}")
            doc.add_paragraph(f"VC Readiness: {report.investment_summary.vc_readiness}")
            doc.add_paragraph(f"TRL: {report.investment_summary.trl}")
            doc.add_paragraph(f"Portfolio Rank: {report.investment_summary.portfolio_rank}")
            doc.add_paragraph(f"Recommendation: {report.investment_summary.recommendation}")

            # Risk Matrix table
            doc.add_heading("Risk Matrix", level=1)
            table = doc.add_table(rows=1, cols=4)
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Risk Category'
            hdr_cells[1].text = 'Severity'
            hdr_cells[2].text = 'Confidence'
            hdr_cells[3].text = 'Mitigation / Recommendation'

            for cat in ["technical", "execution", "market", "competition", "financial", "regulatory", "ip"]:
                item = getattr(report.risk_matrix, cat)
                row_cells = table.add_row().cells
                row_cells[0].text = cat.capitalize()
                row_cells[1].text = item.severity
                row_cells[2].text = f"{item.confidence:.2f}"
                row_cells[3].text = item.recommendation

            # Domains
            domains = [
                ("founder", "Founder & Team"),
                ("product", "Product & Technology"),
                ("market", "Market & Customer"),
                ("competition", "Competitor & Defensibility"),
                ("trl", "Technology Readiness Level"),
                ("financial", "Financial Runway"),
                ("ip", "Intellectual Property"),
                ("risk", "Risk Exposure"),
                ("investment", "Investment Assessment")
            ]
            for field_name, title in domains:
                sect = getattr(report, f"{field_name}_assessment")
                doc.add_heading(f"{title} Assessment", level=1)
                doc.add_paragraph(sect.summary)
                doc.add_paragraph(f"Confidence: {sect.confidence:.2f}")

                doc.add_heading("Observations", level=2)
                for o in sect.observations:
                    doc.add_paragraph(f"- {o.get('text')} (Confidence: {o.get('confidence', 1.0):.2f})", style='List Bullet')

                doc.add_heading("Supporting Evidence", level=2)
                for ev in sect.supporting_evidence:
                    doc.add_paragraph(f"- {ev.get('excerpt')} (Location: {ev.get('location')})", style='List Bullet')

                doc.add_heading("Strengths", level=2)
                for s in sect.strengths:
                    doc.add_paragraph(f"- {s}", style='List Bullet')

                doc.add_heading("Weaknesses", level=2)
                for w in sect.weaknesses:
                    doc.add_paragraph(f"- {w}", style='List Bullet')

                doc.add_heading("Recommendations", level=2)
                for r in sect.recommendations:
                    doc.add_paragraph(f"- {r}", style='List Bullet')

                doc.add_heading("Open Questions", level=2)
                for q in sect.open_questions:
                    doc.add_paragraph(f"- {q}", style='List Bullet')
        else:
            # Legacy Report item
            for field in ["founder_analysis", "product_analysis", "market_analysis", "competition_analysis", "financial_analysis", "trl_analysis", "ip_analysis", "risk_analysis", "committee_decision", "investment_recommendation", "portfolio_position"]:
                val = getattr(report, field, "")
                doc.add_heading(field.replace("_", " ").title(), level=1)
                doc.add_paragraph(val)

        doc.add_heading("Appendix", level=1)
        doc.add_paragraph(getattr(report, "appendix", getattr(report, "explainability_appendix", "")))

        doc.save(file_path)

    @staticmethod
    def export_to_pdf(report: Any, file_path: str) -> None:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib import colors

        doc = SimpleDocTemplate(file_path, pagesize=letter, rightMargin=54, leftMargin=54, topMargin=54, bottomMargin=54)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'PDFTitle',
            parent=styles['Heading1'],
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#0284c7'),
            spaceAfter=15
        )
        h1_style = ParagraphStyle(
            'PDFH1',
            parent=styles['Heading2'],
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#4f46e5'),
            spaceBefore=15,
            spaceAfter=10
        )
        body_style = ParagraphStyle(
            'PDFBody',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            spaceAfter=6
        )
        bullet_style = ParagraphStyle(
            'PDFBullet',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )

        story = []

        story.append(Paragraph(f"Due Diligence Report: {report.startup_name}", title_style))
        story.append(Paragraph(f"<b>Report ID:</b> {report.report_id}", body_style))
        story.append(Paragraph(f"<b>Startup ID:</b> {report.startup_id}", body_style))
        story.append(Paragraph(f"<b>Generated At:</b> {report.generated_at}", body_style))
        story.append(Paragraph(f"<b>Generated By:</b> {report.generated_by}", body_style))
        story.append(Paragraph(f"<b>Graph Hash:</b> {getattr(report, 'graph_hash', 'N/A')}", body_style))
        story.append(Spacer(1, 15))

        story.append(Paragraph("Executive Summary", h1_style))
        overview_para = getattr(report, "executive_summary", "")
        clean_overview = overview_para.replace("#", "").replace("**", "")
        for p in clean_overview.split("\n\n"):
            if p.strip():
                story.append(Paragraph(p.strip(), body_style))

        story.append(Spacer(1, 10))

        if isinstance(report, DueDiligenceReport):
            story.append(Paragraph("Investment Summary", h1_style))
            story.append(Paragraph(f"<b>Investment Readiness:</b> {report.investment_summary.investment_readiness}", body_style))
            story.append(Paragraph(f"<b>Grant Readiness:</b> {report.investment_summary.grant_readiness}", body_style))
            story.append(Paragraph(f"<b>VC Readiness:</b> {report.investment_summary.vc_readiness}", body_style))
            story.append(Paragraph(f"<b>TRL:</b> {report.investment_summary.trl}", body_style))
            story.append(Paragraph(f"<b>Portfolio Rank:</b> {report.investment_summary.portfolio_rank}", body_style))
            story.append(Paragraph(f"<b>Final Recommendation:</b> {report.investment_summary.recommendation}", body_style))
            story.append(Spacer(1, 10))

            story.append(Paragraph("Risk Matrix", h1_style))
            data = [['Category', 'Severity', 'Confidence', 'Mitigation']]
            for cat in ["technical", "execution", "market", "competition", "financial", "regulatory", "ip"]:
                item = getattr(report.risk_matrix, cat)
                data.append([
                    cat.capitalize(),
                    item.severity,
                    f"{item.confidence:.2f}",
                    Paragraph(item.recommendation, body_style)
                ])

            t = Table(data, colWidths=[80, 60, 60, 300])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#6366f1')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.whitesmoke),
                ('ALIGN', (0,0), (-1,-1), 'LEFT'),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('BOTTOMPADDING', (0,0), (-1,0), 8),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ]))
            story.append(t)
            story.append(Spacer(1, 15))

            domains = [
                ("founder", "Founder & Team"),
                ("product", "Product & Technology"),
                ("market", "Market & Customer"),
                ("competition", "Competitor & Defensibility"),
                ("trl", "Technology Readiness Level"),
                ("financial", "Financial Runway"),
                ("ip", "Intellectual Property"),
                ("risk", "Risk Exposure"),
                ("investment", "Investment Assessment")
            ]
            for field_name, title in domains:
                sect = getattr(report, f"{field_name}_assessment")
                story.append(Paragraph(f"{title} Assessment", h1_style))
                story.append(Paragraph(sect.summary, body_style))
                story.append(Paragraph(f"<b>Confidence:</b> {sect.confidence:.2f}", body_style))

                if sect.observations:
                    story.append(Paragraph("<b>Observations:</b>", body_style))
                    for o in sect.observations:
                        story.append(Paragraph(f"&bull; {o.get('text')}", bullet_style))

                if sect.supporting_evidence:
                    story.append(Paragraph("<b>Supporting Evidence:</b>", body_style))
                    for ev in sect.supporting_evidence:
                        story.append(Paragraph(f"&bull; {ev.get('excerpt')} (Location: {ev.get('location')})", bullet_style))

                story.append(Spacer(1, 10))
        else:
            for field in ["founder_analysis", "product_analysis", "market_analysis", "competition_analysis", "financial_analysis", "trl_analysis", "ip_analysis", "risk_analysis", "committee_decision", "investment_recommendation", "portfolio_position"]:
                val = getattr(report, field, "")
                story.append(Paragraph(field.replace("_", " ").title(), h1_style))
                story.append(Paragraph(val, body_style))
                story.append(Spacer(1, 10))

        story.append(Paragraph("Appendix", h1_style))
        app_text = getattr(report, "appendix", getattr(report, "explainability_appendix", ""))
        for p in app_text.split("\n\n"):
            if p.strip():
                story.append(Paragraph(p.strip().replace("#", "").replace("**", ""), body_style))

        doc.build(story)
